import React, { useRef, useState } from 'react';
import { NodeData, NodeType } from '../types';
import { MODEL_OPTIONS } from '../constants';
import { generateAgentResponse } from '../services/geminiService';
import { X, Settings, AlignLeft, Bot, FileText, Mic, Upload, StopCircle, Globe, Sparkles, Loader2, Layout, Users, Clock, DollarSign } from 'lucide-react';

interface PropertiesPanelProps {
  node: NodeData | null;
  isOpen: boolean;
  onClose: () => void;
  onUpdate: (updatedNode: NodeData) => void;
}

export const PropertiesPanel: React.FC<PropertiesPanelProps> = ({ node, isOpen, onClose, onUpdate }) => {
  const [isRecording, setIsRecording] = useState(false);
  const [isGeneratingDesc, setIsGeneratingDesc] = useState(false);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  if (!node) return null;

  const handleChange = (field: string, value: any) => {
    const updatedNode = {
      ...node,
      config: {
        ...node.config,
        [field]: value
      }
    };
    onUpdate(updatedNode);
  };

  const handleLabelChange = (value: string) => {
    onUpdate({ ...node, label: value });
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64String = (reader.result as string).split(',')[1];
        onUpdate({
          ...node,
          config: {
            ...node.config,
            inputType: 'file',
            fileName: file.name,
            fileMimeType: file.type,
            fileData: base64String
          }
        });
      };
      reader.readAsDataURL(file);
    }
  };

  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mediaRecorder = new MediaRecorder(stream, { mimeType: 'audio/webm' });
      mediaRecorderRef.current = mediaRecorder;
      
      const chunks: BlobPart[] = [];
      mediaRecorder.ondataavailable = (e) => chunks.push(e.data);
      mediaRecorder.onstop = () => {
        const blob = new Blob(chunks, { type: 'audio/webm' });
        const reader = new FileReader();
        reader.onloadend = () => {
          const base64String = (reader.result as string).split(',')[1];
          onUpdate({
            ...node,
            config: {
              ...node.config,
              inputType: 'audio',
              audioData: base64String
            }
          });
        };
        reader.readAsDataURL(blob);
        stream.getTracks().forEach(track => track.stop());
      };

      mediaRecorder.start();
      setIsRecording(true);
    } catch (err) {
      console.error('Error accessing microphone:', err);
      alert('Could not access microphone. Please check permissions.');
    }
  };

  const stopRecording = () => {
    if (mediaRecorderRef.current && isRecording) {
      mediaRecorderRef.current.stop();
      setIsRecording(false);
    }
  };

  const handleAutoGenerateDescription = async () => {
    if (node.type !== NodeType.AGENT) return;
    
    setIsGeneratingDesc(true);
    try {
      const prompt = `Based on the following Agent configuration, write a concise, one-sentence description (max 15 words) of what this agent does.
      
      System Instruction: ${node.config.systemInstruction || 'None'}
      Prompt Template: ${node.config.prompt || 'None'}`;

      const response = await generateAgentResponse({
        modelName: 'gemini-3-flash-preview',
        contents: [{ text: prompt }],
      });

      if (response.text) {
        onUpdate({ ...node, description: response.text.trim() });
      }
    } catch (error) {
      console.error("Failed to generate description", error);
    } finally {
      setIsGeneratingDesc(false);
    }
  };

  return (
    <div className={`fixed right-0 top-16 bottom-0 w-96 bg-cream border-l-2 border-slate shadow-2xl transform transition-transform duration-300 ease-in-out z-20 flex flex-col ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}>
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-5 border-b-2 border-slate bg-white">
        <div className="flex items-center gap-2">
          <Settings className="text-teal" size={20} />
          <h2 className="text-xl font-bold text-slate tracking-tight">PROPERTIES</h2>
        </div>
        <button onClick={onClose} className="text-slate hover:text-terra transition-colors bg-cream p-1 border border-slate shadow-hard-sm hover:shadow-none hover:translate-y-[1px] hover:translate-x-[1px]">
          <X size={20} />
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6 space-y-8 bg-cream">
        
        {/* Common Fields */}
        <div className="space-y-4">
          <div>
            <label className="block text-xs font-bold text-slate uppercase tracking-wider mb-2">Label</label>
            <input
              type="text"
              value={node.label}
              onChange={(e) => handleLabelChange(e.target.value)}
              className="w-full px-3 py-3 bg-white border-2 border-slate focus:border-teal focus:ring-0 text-sm font-medium shadow-sm transition-colors"
            />
          </div>
          
          <div>
            <div className="flex justify-between items-center mb-2">
              <label className="block text-xs font-bold text-slate uppercase tracking-wider">Description</label>
              {node.type === NodeType.AGENT && (
                <button 
                  onClick={handleAutoGenerateDescription}
                  disabled={isGeneratingDesc}
                  className="text-[10px] font-bold text-teal flex items-center gap-1 hover:text-terra transition-colors disabled:opacity-50"
                  title="Auto-generate description"
                >
                  {isGeneratingDesc ? <Loader2 size={10} className="animate-spin" /> : <Sparkles size={10} />}
                  AUTO-GEN
                </button>
              )}
            </div>
            <input
              type="text"
              value={node.description || ''}
              onChange={(e) => onUpdate({...node, description: e.target.value})}
              className="w-full px-3 py-3 bg-white border-2 border-slate focus:border-teal text-sm text-slate"
              placeholder="What does this step do?"
            />
          </div>
        </div>

        <div className="border-t-2 border-slate/20" />

        {/* Type Specific Fields */}
        
        {node.type === NodeType.TRIGGER && (
          <div className="space-y-6">
             <h3 className="text-sm font-bold text-teal uppercase tracking-widest flex items-center gap-2 border-b border-teal/20 pb-2">
              <AlignLeft size={16} /> Input Config
            </h3>

            {/* Input Type Selection */}
            <div className="grid grid-cols-4 bg-white border-2 border-slate p-1 gap-1">
               {['structured', 'text', 'file', 'audio'].map((t) => (
                  <button
                    key={t}
                    onClick={() => handleChange('inputType', t)}
                    className={`flex items-center justify-center py-2 text-xs font-bold uppercase transition-all ${node.config.inputType === t || (!node.config.inputType && t === 'text') ? 'bg-teal text-white' : 'text-slate hover:bg-cream'}`}
                    title={t}
                  >
                    {t === 'structured' && <Layout size={16} />}
                    {t === 'text' && <AlignLeft size={16} />}
                    {t === 'file' && <FileText size={16} />}
                    {t === 'audio' && <Mic size={16} />}
                  </button>
               ))}
            </div>

            {/* STRUCTURED INPUT FORM */}
            {node.config.inputType === 'structured' && (
               <div className="space-y-4 bg-white p-4 border-2 border-slate shadow-hard-sm">
                  <div>
                    <label className="block text-[10px] font-bold text-slate/70 uppercase mb-1">Product Name</label>
                    <input
                      type="text"
                      value={node.config.structuredProductName || ''}
                      onChange={(e) => handleChange('structuredProductName', e.target.value)}
                      className="w-full px-2 py-2 border border-slate bg-cream text-sm"
                      placeholder="e.g. FitTrack Pro"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate/70 uppercase mb-1">Target Persona</label>
                    <input
                      type="text"
                      value={node.config.structuredPersona || ''}
                      onChange={(e) => handleChange('structuredPersona', e.target.value)}
                      className="w-full px-2 py-2 border border-slate bg-cream text-sm"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate/70 uppercase mb-1">Key Features</label>
                    <textarea
                      rows={4}
                      value={node.config.structuredFeatures || ''}
                      onChange={(e) => handleChange('structuredFeatures', e.target.value)}
                      className="w-full px-2 py-2 border border-slate bg-cream text-sm font-mono"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate/70 uppercase mb-1">Constraints</label>
                    <textarea
                      rows={2}
                      value={node.config.structuredConstraints || ''}
                      onChange={(e) => handleChange('structuredConstraints', e.target.value)}
                      className="w-full px-2 py-2 border border-slate bg-cream text-sm"
                    />
                  </div>
               </div>
            )}

            {/* Dynamic Input Fields */}
            {(node.config.inputType === 'text' || !node.config.inputType) && (
              <div>
                <label className="block text-xs font-bold text-slate uppercase tracking-wider mb-2">Static Text Input</label>
                <textarea
                  rows={6}
                  value={node.config.staticInput || ''}
                  onChange={(e) => handleChange('staticInput', e.target.value)}
                  className="w-full px-3 py-3 bg-white border-2 border-slate text-sm font-mono focus:border-teal"
                  placeholder="Enter test requirements..."
                />
              </div>
            )}

            {node.config.inputType === 'file' && (
              <div className="space-y-3">
                 <label className="block text-xs font-bold text-slate uppercase tracking-wider">Upload Transcript/Doc</label>
                 <div className="border-2 border-dashed border-slate rounded-none p-6 flex flex-col items-center justify-center bg-white hover:bg-cream transition-colors cursor-pointer" onClick={() => fileInputRef.current?.click()}>
                    <Upload className="text-teal mb-2" size={24} />
                    <span className="text-sm text-slate font-medium">{node.config.fileName || 'CLICK TO UPLOAD'}</span>
                    <input 
                      type="file" 
                      ref={fileInputRef} 
                      className="hidden" 
                      accept=".txt,.pdf,.docx" 
                      onChange={handleFileUpload}
                    />
                 </div>
              </div>
            )}

            {node.config.inputType === 'audio' && (
               <div className="space-y-3">
                 <label className="block text-xs font-bold text-slate uppercase tracking-wider">Record Instructions</label>
                 <div className="flex items-center justify-center p-6 border-2 border-slate bg-white">
                    {!isRecording ? (
                      <button 
                        onClick={startRecording}
                        className="flex flex-col items-center gap-2 group"
                      >
                        <div className="w-14 h-14 bg-terra text-white flex items-center justify-center border-2 border-slate shadow-hard-sm group-hover:shadow-none group-hover:translate-x-[2px] group-hover:translate-y-[2px] transition-all">
                          <Mic size={24} />
                        </div>
                        <span className="text-xs font-bold text-slate">REC</span>
                      </button>
                    ) : (
                      <button 
                        onClick={stopRecording}
                         className="flex flex-col items-center gap-2 group"
                      >
                         <div className="w-14 h-14 bg-slate text-white flex items-center justify-center animate-pulse border-2 border-slate">
                          <StopCircle size={24} />
                        </div>
                        <span className="text-xs font-bold text-slate">STOP</span>
                      </button>
                    )}
                 </div>
               </div>
            )}
            
            <div>
               <label className="block text-xs font-bold text-slate uppercase tracking-wider mb-2">Output Variable</label>
               <input
                type="text"
                value={node.config.outputVar || ''}
                onChange={(e) => handleChange('outputVar', e.target.value)}
                className="w-full px-3 py-2 border-2 border-slate bg-white text-sm font-mono text-teal font-bold"
               />
            </div>
          </div>
        )}

        {node.type === NodeType.AGENT && (
          <div className="space-y-6">
             <h3 className="text-sm font-bold text-teal uppercase tracking-widest flex items-center gap-2 border-b border-teal/20 pb-2">
              <Bot size={16} /> Model Config
            </h3>

            <div>
              <label className="block text-xs font-bold text-slate uppercase tracking-wider mb-2">Model</label>
              <select
                value={node.config.model || 'gemini-3-flash-preview'}
                onChange={(e) => handleChange('model', e.target.value)}
                className="w-full px-3 py-3 border-2 border-slate bg-white text-sm font-bold"
              >
                {MODEL_OPTIONS.map(opt => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            </div>

            <div className="flex items-center justify-between p-3 bg-white border-2 border-slate">
              <div className="flex items-center gap-2">
                <Globe size={16} className="text-teal" />
                <span className="text-sm font-bold text-slate">Google Search</span>
              </div>
              <label className="relative inline-flex items-center cursor-pointer">
                <input 
                  type="checkbox" 
                  className="sr-only peer"
                  checked={node.config.useSearch || false}
                  onChange={(e) => handleChange('useSearch', e.target.checked)}
                />
                <div className="w-11 h-6 bg-cream border-2 border-slate peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full after:content-[''] after:absolute after:top-[4px] after:left-[4px] after:bg-slate after:border after:border-slate after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-teal"></div>
              </label>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate uppercase tracking-wider mb-2">System Instruction</label>
              <textarea
                rows={3}
                value={node.config.systemInstruction || ''}
                onChange={(e) => handleChange('systemInstruction', e.target.value)}
                className="w-full px-3 py-3 border-2 border-slate bg-white text-sm focus:border-teal"
                placeholder="e.g. You are a helpful assistant..."
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate uppercase tracking-wider mb-2">Prompt Template</label>
              <textarea
                rows={6}
                value={node.config.prompt || ''}
                onChange={(e) => handleChange('prompt', e.target.value)}
                className="w-full px-3 py-3 border-2 border-slate bg-white text-sm font-mono focus:border-teal"
                placeholder="Enter prompt with {{variables}}..."
              />
            </div>

            <div>
               <label className="block text-xs font-bold text-slate uppercase tracking-wider mb-2">Output Variable</label>
               <input
                type="text"
                value={node.config.outputVar || ''}
                onChange={(e) => handleChange('outputVar', e.target.value)}
                className="w-full px-3 py-2 border-2 border-slate bg-white text-sm font-mono text-teal font-bold"
               />
            </div>
          </div>
        )}
      </div>
    </div>
  );
};